name: Workflow com Depend de jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1
        run: echo "Exibir uma mensagem de texto para o passo 1"

      - name: Passo 2
        run: echo "Exibir uma mensagem de texto para o passo 2"

      - name: Passo ...
        run: echo "Passo ..."

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest
    
    steps:
      - name: Passo 1
        run: echo "Exibir uma mensagem de texto para o passo 1"

      - name: Passo 2
        run: echo "Exibir uma mensagem de texto para o passo 2"

      - name: Passo ...
        run: echo "Passo ..."
